name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-win:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Build and Publish
        run: yarn electron:build --publish always

  build-linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Yarn install
        run: yarn
      - name: Build and Publish
        run: yarn electron:build --publish always
